/**
 * Custom function to convert the specific Markdown Table output from OpenAI
 * into a clean HTML table structure.
 * @param {string} markdown - The markdown string containing the news table.
 * @returns {string} The HTML representation of the table.
 */
export const markdownTableToHtml = (markdown) => {
    // 1. Split the string into lines and filter out empty ones
    const lines = markdown.trim().split('\n').filter(line => line.trim().length > 0);

    if (lines.length < 3) {
        return '<p style="color: red;">Error: Could not parse news table data.</p>';
    }

    // The first line is the Header Row (e.g., | Priority | Headline |...)
    const headerLine = lines[0];
    
    // The second line is the Separator Row (e.g., |---|---|...) - we ignore this line
    
    // The remaining lines are the Data Rows
    const dataLines = lines.slice(2); 

    // Helper function to process a line into cells
    const processLineToCells = (line) => {
      return line.split('|').slice(1, -1).map(cell => cell.trim());
    };

    let html = '<table>';

    // 1. Table Header (TH)
    const headers = processLineToCells(headerLine);
    html += '<thead><tr>';
    headers.forEach(header => {
        html += `<th>${header}</th>`;
    });
    html += '</tr></thead>';

    // 2. Table Body (TD)
    html += '<tbody>';
    dataLines.forEach(dataLine => {
        const cells = processLineToCells(dataLine);
        html += '<tr>';
        cells.forEach((cell, index) => {
            // Special handling for the Headline/Link column (assuming it's the second cell, index 1)
            // This is crucial for making the link clickable in the email.
            if (index === 1 && cells.length > 7 && cells[7].startsWith('http')) {
                // If the link column (index 7) is present and starts with 'http', use it for the headline
                const link = cells[7];
                html += `<td><a href="${link}" target="_blank" style="color: #007bff; text-decoration: none; font-weight: bold;">${cell}</a></td>`;
            } else {
                html += `<td>${cell}</td>`;
            }
        });
        html += '</tr>';
    });
    html += '</tbody>';

    html += '</table>';

    return html;
};

/**
 * Combines the formatted news and weather into a complete email body.
 * @param {string} newsSummary - The Markdown news table.
 * @param {string} weatherSummaryHtml - The HTML weather report (now returned directly from weather.js).
 * @returns {string} The final, complete HTML email body.
 */
export const buildEmailHtml = (newsSummary, weatherSummaryHtml) => { // NOTE: Renamed arg for clarity
    const newsHtml = markdownTableToHtml(newsSummary);

    // Apply basic inline styling for email compatibility
    return `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                h1 { color: #004d99; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                h2 { color: #007bff; margin-top: 30px; }
                table { width: 100%; border-collapse: collapse; margin-top: 15px; }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; vertical-align: top; }
                th { background-color: #f0f8ff; color: #004d99; }
                .weather-box { background-color: #e6f7ff; padding: 15px; border-radius: 8px; border: 1px solid #b3e0ff; }
            </style>
        </head>
        <body>
            <h1>🌤️ Your Daily Morning Briefing 📰</h1>

            <h2>Today's Weather Forecast</h2>
            <div class="weather-box">
                ${weatherSummaryHtml} 
            </div>

            <h2>Top 5 Strategic Tech Headlines</h2>
            ${newsHtml}

            <p style="margin-top: 40px; font-size: 12px; color: #888;">Briefing generated by your Node.js script and OpenAI.</p>
        </body>
        </html>
    `;
};